import numpy as np

trainfile_path = './Data/train_enc.csv'
testfile_path = './Data/test_enc.csv'

url = 'https://www.davidgoricanec-noip.ddns.net/send_anomaly_detection'

col_names = np.loadtxt('./Data/final_col_names.txt', delimiter=',', dtype=str)
col_length = len(col_names)-1

threshold = 0.2

final_col_names = ["duration", "src_bytes", "dst_bytes", "land", "wrong_fragment",
             "urgent", "hot", "num_failed_logins", "logged_in", "num_compromised", "root_shell", "su_attempted", "num_root",
             "num_file_creations", "num_shells", "num_access_files", "num_outbound_cmds", "is_host_login", "is_guest_login", 
             "count", "srv_count", "serror_rate", "srv_serror_rate", "rerror_rate", "srv_rerror_rate", "same_srv_rate",
             "diff_srv_rate", "srv_diff_host_rate", "dst_host_count", "dst_host_srv_count", "dst_host_same_srv_rate", 
             "dst_host_diff_srv_rate", "dst_host_same_src_port_rate", "dst_host_srv_diff_host_rate", "dst_host_serror_rate", 
             "dst_host_srv_serror_rate", "dst_host_rerror_rate", "dst_host_srv_rerror_rate", "Protocol_icmp","Protocol_tcp",
             "Protocol_udp","service_IRC","service_X11","service_Z39_50","service_auth","service_bgp","service_courier","service_csnet_ns",
             "service_ctf","service_daytime","service_discard","service_domain","service_domain_u","service_echo","service_eco_i","service_ecr_i",
             "service_efs","service_exec","service_finger","service_ftp","service_ftp_data","service_gopher","service_hostnames","service_http",
             "service_http_443","service_imap4","service_iso_tsap","service_klogin","service_kshell","service_ldap","service_link","service_login",
             "service_mtp","service_name","service_netbios_dgm","service_netbios_ns","service_netbios_ssn","service_netstat","service_nnsp","service_nntp",
             "service_ntp_u","service_other","service_pm_dump","service_pop_2","service_pop_3","service_printer","service_private","service_remote_job","service_rje",
             "service_shell","service_smtp","service_sql_net","service_ssh","service_sunrpc","service_supdup","service_systat","service_telnet","service_tftp_u",
             "service_tim_i","service_time","service_urp_i","service_uucp","service_uucp_path","service_vmnet","service_whois","flag_OTH","flag_REJ","flag_RSTO",
             "flag_RSTOS0","flag_RSTR","flag_S0","flag_S1","flag_S2","flag_S3","flag_SF","flag_SH","class_"]


ports_mapping= {
    21: 'ftp',
    22: 'ssh',
    23: 'telnet',
    25: 'smtp',
    42: 'nameserver',
    43: 'whois',
    53: 'domain',
    67: 'dhcp',
    68: 'dhcp',
    69: 'tftp',
    70: 'gopher',
    79: 'finger',
    80: 'http',
    88: 'kerberos',
    109: 'pop2',
    110: 'pop3',
    111: 'rpcbind',
    113: 'ident',
    119: 'nntp',
    123: 'ntp',
    135: 'epmap',
    137: 'netbios-ns',
    138: 'netbios-dgm',
    139: 'netbios-ssn',
    143: 'imap',
    161: 'snmp',
    162: 'snmp-trap',
    179: 'bgp',
    194: 'irc',
    389: 'ldap',
    443: 'http_443',
    445: 'microsoft-ds',
    465: 'smtps',
    512: 'exec',
    513: 'login',
    514: 'shell',
    515: 'printer',
    543: 'klogin',
    544: 'kshell',
    548: 'afp',
    554: 'rtsp',
    587: 'submission',
    631: 'ipp',
    646: 'ldp',
    873: 'rsync',
    902: 'vmware-auth',
    993: 'imaps',
    995: 'pop3s',
    1080: 'socks',
    1194: 'openvpn',
    1433: 'ms-sql-s',
    1434: 'ms-sql-m',
    1521: 'oracle',
    1723: 'pptp',
    1725: 'steam',
    1755: 'rtmp',
    1900: 'upnp',
    2082: 'cpanel',
    2083: 'cpanel-ssl',
    2086: 'whm',
    2087: 'whm-ssl',
    2095: 'webmail',
    2096: 'webmail-ssl',
    2222: 'directadmin',
    3306: 'mysql',
    3389: 'rdp',
    5432: 'postgresql',
    5900: 'vnc',
    5938: 'teamviewer',
    8080: 'http-proxy',
    8443: 'https-alt',
    10000: 'webmin'
}